MySteamPlay/Controllers/GameListController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MySteamPlay.Models;
using Microsoft.AspNet.Identity;
using Newtonsoft.Json;
using PortableSteam;

namespace MySteamPlay.Controllers
{
    public class GameListController : DataBaseController
    {
        // GET: GameLists
        public async Task<ActionResult> Index(string searchString)
        {
            // TODO Error Handling for when user is not logged in
            string currentUserID = User.Identity.GetUserId();

            //Returned data must fit into GameListViewModel
            var GameQuery = from gdesc in Database.GDescriptions
                            join game in Database.Games on gdesc.appID equals game.appID
                            join taglist in Database.TagLists on gdesc.Tags.ID equals taglist.ID
                            where gdesc.userId == currentUserID
                            select new GameListViewModel
                            {
                                Name = game.name,
                                LogoUrl = game.img_logo_url,
                                IconUrl = game.img_icon_url,
                                HeaderUrl = game.img_header_url,
                                Playtime = gdesc.playtime_forever,
                                Comment = gdesc.userComments,
                                UserId = gdesc.userId,
                                AppId = game.appID,
                                Visible = gdesc.visible,
                                GameTags = taglist,
                                AllTags = Database.Tags.ToList()
                            };
            if (!String.IsNullOrWhiteSpace(searchString))
            {
                GameQuery = GameQuery.Where(s => s.Name.Contains(searchString));
            }
            return View(GameQuery);
        }

        // GET: GameLists/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            // TODO Error Handling for when user is not logged in
            string currentUserID = User.Identity.GetUserId();

            Game selectedGame = await Database.Games.FindAsync(id);
            if (selectedGame == null)
            {
                return HttpNotFound();
            }
            var currTagList = selectedGame.GameDescriptions.Where(i => i.userId == currentUserID).FirstOrDefault().Tags;

            List<int> tags = new List<int>();

            if (currTagList != null)
            {
                foreach (var item in currTagList.Tags)
                {
                    tags.Add(item.tagID);
                }
            }

            var GameQuery = from gdesc in Database.GDescriptions
                            join game in Database.Games on gdesc.appID equals game.appID
                            join taglist in Database.TagLists on gdesc.Tags.ID equals taglist.ID
                            where gdesc.userId == currentUserID &&
                                  gdesc.appID == id
                            select new EditGameListViewModel
                            {
                                Name = game.name,
                                LogoUrl = game.img_logo_url,
                                IconUrl = game.img_icon_url,
                                HeaderUrl = game.img_header_url,
                                Playtime = gdesc.playtime_forever,
                                Comment = gdesc.userComments,
                                UserId = gdesc.userId,
                                AppId = game.appID,
                                GameDescId = gdesc.ID,
                                Visible = gdesc.visible,
                                AllTags = Database.Tags.ToList(),
                                GameTagIds = tags
                            };

            EditGameListViewModel foundGame = GameQuery.Single();

            return View(foundGame);
        }

        // GET: GameLists/Create
        public ActionResult Create()
        {
            string currentUserID = User.Identity.GetUserId();
            ApplicationUser currentUser = Database.Users.Find(currentUserID);
            string providerKey = currentUser.Logins.First().ProviderKey;

            providerKey = providerKey.Substring(providerKey.Length - 17);

            SteamWebAPI.SetGlobalKey(Security.apiKey);

            var identity = SteamIdentity.FromSteamID(Int64.Parse(providerKey));

            //JSON response from Steam 
            var response = SteamWebAPI.General().IPlayerService().GetOwnedGames(identity).IncludeAppInfo().GetResponse();

            //Iterate through each item and add it to database
            foreach (var res in response.Data.Games)
            {
                TimeSpan timeSpan = res.PlayTimeTotal;

                int totalHours = (int)timeSpan.TotalHours;

                TagList tagList = new TagList()
                {
                    appID = res.AppID,
                    userID = currentUserID
                };

                GameDescrip gameDesc = new GameDescrip()
                {
                    appID = res.AppID,
                    playtime_forever = totalHours,
                    userId = currentUserID,
                    visible = true, //True by default for now.
                    Tags = tagList
                };

                Game game = new Game();

                if (res.Name != null)
                {
                    game.name = res.Name;
                }
                else
                {
                    game.name = res.AppID.ToString();
                }
                game.appID = res.AppID;
                game.img_header_url = "http://cdn.akamai.steamstatic.com/steam/apps/" + res.AppID + "/header.jpg";
                game.img_icon_url = "http://media.steampowered.com/steamcommunity/public/images/apps/" + res.AppID + "/" + res.IconUrl + ".jpg";
                game.img_logo_url = "http://media.steampowered.com/steamcommunity/public/images/apps/" + res.AppID + "/" + res.LogoUrl + ".jpg";

                //Ensure User entry for game doesn't exist in table
                bool doesLibraryExist = (Database.GDescriptions.Any(u => u.userId.Equals(gameDesc.userId)) &&
                    Database.GDescriptions.Any(a => a.appID.Equals(game.appID))); //AppID
                //Ensure Game doesn't already exist in game table
                bool doesGameExist = Database.Games.Any(a => a.appID.Equals(game.appID));

                if (doesLibraryExist)
                {
                    // Do nothing
                }
                else
                {
                    if (doesGameExist)
                    {
                        //Add existing game object
                        gameDesc.Game = Database.Games.Where(a => a.appID == game.appID).SingleOrDefault();
                    }
                    else
                    {
                        //add newly created game object
                        gameDesc.Game = game;
                        Database.Games.Add(game);
                    }
                    //Add User Record for game
                    Database.GDescriptions.Add(gameDesc);
                }

            }
            currentUser.GameCount = response.Data.GameCount;
            Database.SaveChanges();

            return RedirectToAction("Index");
        }

        // GET: GameLists/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Game selectedGame = await Database.Games.FindAsync(id);

            if (selectedGame == null)
            {
                return HttpNotFound();
            }

            string currentUserID = User.Identity.GetUserId();

            var currTagList = selectedGame.GameDescriptions.Where(i => i.userId == currentUserID).FirstOrDefault().Tags;

            List<int> tags = new List<int>();

            if (currTagList != null)
            {
                foreach (var item in currTagList.Tags)
                {
                    tags.Add(item.tagID);
                }
            }
            var GameQuery = from gdesc in Database.GDescriptions
                            join game in Database.Games on gdesc.appID equals game.appID
                            join taglist in Database.TagLists on gdesc.Tags.ID equals taglist.ID
                            where gdesc.userId == currentUserID &&
                                  gdesc.appID == id
                            select new EditGameListViewModel
                            {
                                Name = game.name,
                                LogoUrl = game.img_logo_url,
                                IconUrl = game.img_icon_url,
                                HeaderUrl = game.img_header_url,
                                Playtime = gdesc.playtime_forever,
                                Comment = gdesc.userComments,
                                UserId = gdesc.userId,
                                AppId = game.appID,
                                GameDescId = gdesc.ID,
                                Visible = gdesc.visible,
                                AllTags = Database.Tags.ToList(),
                                GameTagIds = tags
                            };

            EditGameListViewModel foundGame = GameQuery.Single();

            return View(foundGame);
        }

        // POST: GameLists/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 

MySteamPlay/Views/Shared/LibraryPage.cshtml
@model List<mvcajaxinfinitescroll.Models.LibraryItem>
@for each (var item in Model)
{
    <div style="height: 300px; background-color: #F3F3F3; margin-bottom: 30px;">
        <div style="padding: 30px; 
        font-size: 25px; color: #7b4f9d">@item.steamID</div>
        <div style="padding-left: 30px; 
        font-size: 18px;">appId: @item.appID</div>
        <div style="padding-left: 30px; 
        font-size: 18px;">playtime_forever: @item.playtimeForever</div>
        <div style="padding-left: 30px; 
        font-size: 18px;">userComments: @item.userComments $</div>
    </div>
}   


@*MySteamPlay.Models.LibraryItem

@{
    ViewBag.Title = "LibraryPage";
}

<h2>LibraryPage</h2>

<div>
    <h4>LibraryItem</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.steamID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.steamID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.appID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.appID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.playtime_forever)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.playtime_forever)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.userComments)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.userComments)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.visible)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.visible)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.sortOrder)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.sortOrder)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    @Html.ActionLink("Back to List", "Index")
</p>*@

MySteamPlay/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My Steam Play</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("My Steam Play", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>

                    @if (User.Identity.IsAuthenticated)
                    {
                        <li>@Html.ActionLink("Game List", "Index", "GameList")</li>
					    <li>@Html.ActionLink("Account Settings", "Index", "Manage")</li>
                    }
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        
    </div>
        <footer class="container">
            <hr />
            <ul class="nav nav-pills n">
                <li>@Html.ActionLink("Disclaimer", "Disclaimer", "Home")</li>
                <li>@Html.ActionLink("About Us", "About", "Home")</li>
                <li>@Html.ActionLink("Frequently Asked Questions - FAQ", "Faq", "Home")</li>
                <li><a href="http://steampowered.com/">Powered by Steam</a></li>
                <li class="pull-right">&copy; @DateTime.Now.Year - My Steam Play</li>
            </ul>
        </footer>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>